version: '3'

volumes:
  postgres_data:
    driver: local
  keycloak_data: # Add a new volume for Keycloak
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    volumes:
      - keycloak_data:/opt/jboss/keycloak # Mount the keycloak_data volume to the appropriate path
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ['start-dev --http-relative-path=/auth']
    ports:
      - 8080:8080
    depends_on:
      - postgres
