version: '3'

volumes:
  mysql-data:
    driver: local
    
networks:
  backend:
  frontend:    
  
services:

    # PETPAL CORE SERVICE
  petpal-core:
    image: petpal-core:1.0.0
    build:
        context: petpal-core
        dockerfile: Dockerfile
    restart: "always"
    networks:
      - backend
      - frontend
    ports:
      - "8081:8080"
      - "5005:5005"
    environment:
      - LOG_LEVEL=DEBUG
      - JAVA_DEBUG=true
      - JAVA_DEBUG_PORT=*:5005
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - DB_HOST=mysql_core
      - DB_PORT=3306
      - DB_NAME=petpal
      - DB_USER=petpalcore
      - DB_PWD=petpal
      - DB_SSL=false
    depends_on:
     - mysql_core
    logging:
        driver: local
        options:
            max-size: "20m"
            max-file: "10"
    
    # Database Service (Mysql)
  mysql_core:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: petpal
      MYSQL_USER: petpalcore
      MYSQL_PASSWORD: petpal
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
